list: $/shohabbos/invest/models/deposit/columns.yaml
modelClass: Shohabbos\Invest\Models\Deposit
title: Deposits
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'shohabbos/invest/deposits/update/:id'
